### ISSUE TITLE
Clearer Installation Instructions

### ISSUE THREAD

**Issue by Qasimmodo** [lirien/moshbot#7]
Using Ubuntu.

**Comment by Qasimmodo** [comment]
Ideally a Wiki.

**Comment by lirien** [comment]
This is a personal project for a twitter bot, so the instructions are for my own use. I left the source code visible in case anybody wanted to see it, but this project wasn't intended to be a tool for others to use. If you want to make a similar project, it shouldn't be too hard to figure it out.
